import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "shaah1d.vercel.app",
  title: "shaah1d",
  description: "Hi, I'm Gxuri - Got ideas you are itching to bring to life? Let's collaborate and make it happen!",
  keywords: [
    "gurvinder singh",
    "guri",
    "gurvinder singh 02",
    "portfolio",
    "guri portfolio",
    "guri 100x dev",
    "full stack developer",
    "designer",
    "web developer",
    "web designer",
    "react developer",
    "react designer",
    "next.js developer",
    "next.js designer",
    "gurvinder singh portfolio",
    "gurvinder singh website",
    "gurvinder singh portfolio website",
    "gurvinder singh portfolio website 2024",
    "gurvinder singh portfolio 2024",
    "gxuri",
    "gxuri in",
    "gxuri.in", 
    "gxuri portfolio",
    "gxuri portfolio 2024",
    "gxuri portfolio website",
    "gxuri portfolio website 2024",
    "gxuri portfolio 2024 website",
    "gxuri portfolio 2024 website 2024",
    "gxuri portfolio 2024 website 2025",
    "gxuri portfolio 2025",
    "gxuri portfolio 2025 website",
    "gxuri portfolio 2025 website 2025",
  ],
  siteUrl: "https://dev.gxuri.in",
  creator: {
    name: "Gxuri",
    url: "https://dev.gxuri.in",
  },
  ogImage: "https://dev.gxuri.in/meta_thumb2.png",
  links: {
    x: "https://x.com/guri_who",
    github: "https://github.com/Gurvinder-Singh02",
  }
}