import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "shaahid.xyz",
  title: "shaah1d",
  description: "Hi!, I am Shaahid, and I develop FullStack Web Applications using Nextjs and I also write smart contracts",
  keywords: [
    "shaahid shaikh",
    "shaahid",
    "shaah1d",
    "portfolio",
    "shaahid portfolio",
    "shaahid 100x dev",
    "full stack developer",
    "designer",
    "web developer",
    "web designer",
    "react developer",
    "react designer",
    "next.js developer",
    "next.js designer",
    "shaahid shaikh portfolio",
    "shaahid shaikh website",
    "shaahid shaikh portfolio website",
    "shaahid shaikh portfolio website 2025",
    "shaahid shaikh portfolio 2025",
    "shaah1d",
    "shaah1d in",
    "shaah1d.in", 
    "shaah1d portfolio",
    "shaah1d portfolio 2025",
    "shaah1d portfolio website",
    "shaah1d portfolio website 2025",
    "shaah1d portfolio 2025 website",
    "shaah1d portfolio 2025 website 2025",
    "shaah1d portfolio 2025 website 2025",
    "shaah1d portfolio 2025",
    "shaah1d portfolio 2025 website",
    "shaah1d portfolio 2025 website 2025",
  ],
  siteUrl: "https://shaah1d.vercel.app",
  creator: {
    name: "shaah1d",
    url: "https://shaah1d.vercel.app",
  },
  ogImage: "https://shaah1d.vercel.app/favicon.jpg",
  links: {
    x: "https://x.com/shaa1d",
    github: "https://github.com/shaah1d",
  }
}